# Week 3 Functions and Packages

In [2]:
# string to experiment with: room
room = "poolhouse"

# Use upper() on room: room_up
room_up = room.upper()

# Print out room and room_up
print (room)
print (room_up)

# Print out the number of o's in room
print (room.count("o"))

poolhouse
POOLHOUSE
3


In [5]:
# Create list areas
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

# Print out the index of the element 20.0
print(areas.index(20.0))

# Print out how often 14.5 appears in areas
print (areas.count(14.5))


2
0


In [7]:
# Create list areas
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

# Use append twice to add poolhouse and garage size
areas.append(24.5)
areas.append(15.45)

# Print out areas
print (areas)

# Reverse the orders of the elements in areas
areas.reverse()

# Print out areas
print (areas)

[11.25, 18.0, 20.0, 10.75, 9.5, 24.5, 15.45]
[15.45, 24.5, 9.5, 10.75, 20.0, 18.0, 11.25]


In [17]:
import numpy as np
print (numpy.array ([1,2,3]))
print (np.array([1,2,3]))

[1 2 3]
[1 2 3]


In [19]:
print (numpy.array(areas))

[ 15.45  24.5    9.5   10.75  20.    18.    11.25]


In [21]:
# Definition of radius
r = 192500

# Import radians function of math package
from math import radians

# Travel distance of Moon if 12 degrees. Store in dist.
dist = r * radians(12)

# Print out dist
print(dist)

40317.10572106901
