# Week 4 numpy

In [1]:
import numpy as np

In [2]:
# Create list baseball
baseball = [180, 215, 210, 210, 188, 176, 209, 200]

# Import the numpy package as np
import numpy as np

# Create a Numpy array from baseball: np_baseball
np_baseball = np.array(baseball)

# Print out type of np_baseball
print(type(np_baseball))

<class 'numpy.ndarray'>


In [7]:
# height is available as a regular list
height = [74,74,78,73]

# Import numpy
import numpy as np

# Create a Numpy array from height: np_height
np_height = np.array(height)

# Print out np_height
print(np_height)

# Convert np_height to m: np_height_m
np_height_m = np_height * 0.0254

# Print np_height_m
print(np_height_m)

[74 74 78 73]
[ 1.8796  1.8796  1.9812  1.8542]


In [11]:
# height and weight are available as a regular lists
weight = [130, 120, 180, 152]

# Import numpy
import numpy as np

# Create array from height with correct units: np_height_m
np_height_m = np.array(height) * 0.0254

# Create array from weight with correct units: np_weight_kg
np_weight_kg = np.array(weight) * 0.453592 

# Calculate the BMI: bmi
bmi = np_weight_kg / (np_height_m ** 2)

# Print out bmi
print (bmi)

[ 16.69082739  15.40691759  20.80085817  20.05376036]


In [14]:
# height and weight are available as a regular lists

# Import numpy
import numpy as np

# Calculate the BMI: bmi
np_height_m = np.array(height) * 0.0254
np_weight_kg = np.array(weight) * 0.453592
bmi = np_weight_kg / np_height_m ** 2

# Create the light array
light = bmi < 21

# Print out light
print (light)

# Print out BMIs of all baseball players whose BMI is below 21
print (bmi[light])


[ True  True  True  True]
[ 16.69082739  15.40691759  20.80085817  20.05376036]
